src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [

    # UI
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('testify/', include('testify.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/testify/api/urls.py
from django.urls import path

from testify.api.views import TestListCreateView, TestUpdateDeleteView

app_name = 'testify'

urlpatterns = [
    path('tests/', TestListCreateView.as_view(), name='list'),
    path('tests/<int:pk>/', TestUpdateDeleteView.as_view(), name='details'),
]

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, TestDetailView, TestListView, TestRunnerView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),
]

src/testify/models.py
from accounts.models import User

from core.models import BaseModel

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.name}'


class Test(models.Model):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)
    description = models.TextField(max_length=512, null=True, blank=True)

    def __str__(self):
        return f'{self.text}'


class Answer(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='answers', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class TestResult(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='test_results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='test_results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)]
    )
    current_order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])

    def __str__(self):
        return f'{self.test} ran by {self.user.full_name()} at {self.write_date}'

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    def time_spent(self):
        return self.write_date - self.create_date

    def score(self):
        return (self.num_correct_answers / self.test.questions.count()) * 100

    @classmethod
    def current_unfinished_run(cls, user, test_id):
        qs = cls.objects.filter(
            user=user,
            state=cls.STATE.NEW,
            test=test_id,
        )
        return qs.first() if qs.count() else None

    @staticmethod
    def best_result(test_id):
        queryset = TestResult.objects.filter(test=test_id)
        if queryset.count() > 0:
            obj = queryset.extra(select={
                'points': 'num_correct_answers - num_incorrect_answers', 'duration': 'write_date - create_date'},
                order_by=['-points', 'duration'])[0]
            result = f'{obj.user} scored {obj.num_correct_answers} points'
            return result
        else:
            result = 'No one has done this test yet'
            return result

    @staticmethod
    def last_run(test_id):
        if TestResult.objects.filter(test=test_id).count() > 0:
            ob = TestResult.objects.filter(test=test_id).order_by('-write_date').first()
            result = ob.write_date
            return result
        else:
            result = 'No one has run this test yet'
            return result


class UserResponse(models.Model):
    test_result = models.ForeignKey(to=TestResult, related_name='users_answers', on_delete=models.CASCADE)
    question = models.ForeignKey(to=Question, related_name='users_answers', on_delete=models.CASCADE)
    user_response = models.ForeignKey(to=Answer, related_name='users_answers', on_delete=models.CASCADE)

    def __str__(self):
        return self.user_response.text

src/testify/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, HiddenInput, ModelForm, modelformset_factory

from testify.models import Answer, Question


class AnswerAdminForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = '__all__'


class AnswerForm(ModelForm):
    is_selected = forms.BooleanField(required=False)
    id = forms.IntegerField(required=False) # noqa

    class Meta:
        model = Answer
        fields = ['text', 'is_selected', 'id']

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['text'].widget = HiddenInput()
        self.fields['id'].widget = HiddenInput()


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

    def clean(self):
        pass


class QuestionsInlineFormSet(BaseInlineFormSet):
    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError('Quantity of question is out of range ({}..{})'.format(
                self.instance.QUESTION_MIN_LIMIT, self.instance.QUESTION_MAX_LIMIT))

        order_number_list = []
        for form in self.forms:
            order_number_list.append(form.cleaned_data['order_number'])

        if 1 not in order_number_list:
            raise ValidationError('Numeration starts with one')

        previous = 1
        for i in sorted(order_number_list)[1:]:
            if i != previous + 1:
                raise ValidationError('All numbers increase with step 1')
            previous = i


class AnswersInlineFormSet(BaseInlineFormSet):
    def clean(self):
        if not (self.instance.ANSWER_MIN_LIMIT <= len(self.forms) <= self.instance.ANSWER_MAX_LIMIT):
            raise ValidationError('Quantity of answer is out of range ({}..{})'.format(
                self.instance.ANSWER_MIN_LIMIT, self.instance.ANSWER_MAX_LIMIT))

        num_correct_answers = sum([
            1
            for form in self.forms
            if form.cleaned_data['is_correct']
        ])

        if num_correct_answers == 0:
            raise ValidationError('At LEAST one answer must be correct!')

        if num_correct_answers == len(self.forms):
            raise ValidationError('Not allowed to select ALL answers!')


AnswerFormSet = modelformset_factory(
    model=Answer,
    form=AnswerForm,
    extra=0
)

src/testify/api/views.py
from rest_framework import generics

from testify.api.serializers import TestSerializer
from testify.models import Test


class TestListCreateView(generics.ListCreateAPIView):
    authentication_classes = []
    permission_classes = []
    queryset = Test.objects.all()
    serializer_class = TestSerializer


class TestUpdateDeleteView(generics.RetrieveUpdateAPIView):
    queryset = Test.objects.all()
    serializer_class = TestSerializer

src/testify/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, ListView

from testify.forms import AnswerFormSet
from testify.models import Question, Test, TestResult


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    template_name = 'list.html'
    context_object_name = 'tests'


class TestDetailView(LoginRequiredMixin, DetailView):
    model = Test
    template_name = 'details.html'
    context_object_name = 'test'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        test_id = self.kwargs['id']
        all_results = TestResult.objects.filter(test=test_id)
        context['all_results'] = all_results
        context['best_result'] = TestResult.best_result(test_id)
        context['last_run'] = TestResult.last_run(test_id)
        context['current_unfinished_run'] = TestResult.current_unfinished_run(
            user=self.request.user,
            test_id=test_id,
        )
        return context


class TestRunnerView(LoginRequiredMixin, View):

    def get(self, request, id):  # noqa
        TestResult.objects.get_or_create(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
            defaults=dict(
                current_order_number=1
            )
        )

        return redirect(reverse('tests:next', args=(id, )))


class QuestionView(LoginRequiredMixin, View):

    def get(self, request, id):  # noqa
        test_result = TestResult.objects.filter(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
        )

        if test_result.count() == 0:
            return redirect(reverse('tests:details', args=(id,)))

        test_result = test_result.first()

        order_number = test_result.current_order_number
        question = Question.objects.get(test_id=id, order_number=order_number)
        answers = question.answers.all()
        form_set = AnswerFormSet(queryset=answers)

        return render(
            request=request,
            template_name='question.html',
            context={
                'question': question,
                'form_set': form_set,
            }
        )


    def post(self, request, id):  # noqa
        test_result = TestResult.objects.filter(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
        )

        if test_result.count() == 0:
            return redirect(reverse('tests:details', args=(id,)))

        test_result = test_result.first()

        order_number = test_result.current_order_number
        question = Question.objects.get(test__id=id, order_number=order_number)
        answers = question.answers.all()
        form_set = AnswerFormSet(data=request.POST)

        # for form in form_set:
        #     if 'is_selected' in form.changed_data:
        #         answer = Answer.objects.get(id=form.instance.id)
        #         user_response = UserResponse.objects.create(
        #             test_result=test_result,
        #             question=question,
        #             user_response=answer,
        #         )
        #         user_response.save()

        possible_choices = len(form_set.forms)
        selected_choices = [
            'is_selected' in form.changed_data
            for form in form_set.forms
        ]

        correct_choices = sum(
            answer.is_correct == choice
            for answer, choice in zip(answers, selected_choices)
        )

        point = int(correct_choices == possible_choices)

        test_result = TestResult.objects.get(
            user=request.user,
            test=question.test,
            state=TestResult.STATE.NEW
        )

        test_result.num_correct_answers += point
        test_result.num_incorrect_answers += (1 - point)
        test_result.current_order_number += 1
        test_result.save()

        if order_number == question.test.questions.count():
            test_result.state = TestResult.STATE.FINISHED
            test_result.save()
            # user_responses = UserResponse.objects.filter(
            #     test_result=test_result.id
            # )
            # questions = Question.objects.filter(test=id)

            return render(
                request=request,
                template_name='finish.html',
                context={
                    'test_result': test_result,
                    # 'user_responses': user_responses,
                    # 'questions': questions,
                }
            )
        else:
            return redirect(reverse('tests:next', args=(id,)))

src/testify/templates/details.html
{% extends 'base.html' %}

{% block header %}
    <h1>{{ test }}</h1>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Test info</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Description</td>
                        <td>{{ test.description }}</td>
                      </tr>
                      <tr>
                        <td>Num of questions</td>
                        <td>{{ test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Num of runs</td>
                        <td>{{ test.test_results.count }}</td>
                      </tr>
                      <tr>
                        <td>Best result</td>
                        <td>{{ best_result }}</td>
                      </tr>
                      <tr>
                        <td>Last run</td>
                        <td>{{ last_run }}</td>
                      </tr>
                      {% if current_unfinished_run %}
                      <tr>
                        <td>Current open run</td>
                        <td>{{ current_unfinished_run.create_date }}</td>
                      </tr>
                      {% endif %}
                    </tbody>
                  </table>
            </div>
            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{{ test.image.url }}">
                </div>

                {% if current_unfinished_run %}
                    <div class="d-flex justify-content-center mt-5 mb-5" >
                            <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-warning">CONTINUE ▶️</a>
                    </div>
                {% else %}
                <div class="d-flex justify-content-center mt-5 mb-5" >
                        <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-success">START ▶️</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>

{% if last_run != 'No one has run this test yet' %}
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>User</th>
            <th>Started</th>
            <th>Time spent</th>
            <th>Points</th>
        </tr>
    {% for result in all_results %}
        <tr>
            <td>{{ result.id }}</td>
            <td>{{ result.user }}</td>
            <td>{{ result.write_date }}</td>
            <td>{{ result.time_spent }}</td>
            <td>{{ result.points }}</td>
        </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}

src/testify/templates/finish.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
    <h1>Congratulations!!!</h1>
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">You answered all the questions</div>
        </div>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>{{ test_result.test.title }}</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Correct answers</td>
                        <td>{{ test_result.num_correct_answers }} / {{ test_result.test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Score</td>
                        <td>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" style="width:{{ test_result.score }}%" aria-valuenow="{{ test_result.score }}" aria-valuemin="0" aria-valuemax="100">{{ test_result.score|floatformat:2 }}%</div>
                            </div>
                        </td>
                      </tr>
                      <tr>
                        <td>Time spent</td>
                        <td>{{ test_result.time_spent }}</td>
                      </tr>
                      <tr>
                        <td>Time finished</td>
                        <td>{{ test_result.write_date }}</td>
                      </tr>
                      <tr>
                        <td>Points</td>
                        <td>{{ test_result.points }}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{% static 'common/img/finish.jpg' %}">
                </div>

                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a href="{% url 'tests:list' %}" type="button" class="btn-lg btn-success">START ANOTHER TEST ▶️</a>
                </div>

            </div>
        </div>
    </div>

<!--    <div class="col-sm">-->
<!--        {% for question in questions %}-->
<!--            <h3>For the question: "{{question}}"</h3>-->
<!--            {% for user_response in user_responses %}-->
<!--                {% if question.id == user_response.question.id %}-->
<!--                    <h3>You answered: "{{user_response}}"</h3>-->
<!--                {% endif %}-->
<!--            {% endfor %}-->
<!--        {% endfor %}-->
<!--    </div>-->

{% endblock %}

src/testify/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
    <title>Tests list</title>
{% endblock %}

{% block header%}
<h3>Tests list</h3>
{% endblock %}

{% block content %}
    {% if tests %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Level</th>
                  <th></th>
                </tr>
            </thead>

            {% for test in tests %}
                <tr>
                    <td><img class="rounded-circle p-1 m-1" width="150" height="150"  src="{{ test.image.url }}"></td>
                    <td> {{ test.title }}</td>
                    <td> {{ test.description }}</td>
                    <td>
                        <div class="d-flex justify-content-center">
                            <img class="rounded-circle p-1 m-1" width="90" height="40" src="{% static 'common/img/level_'%}{{ test.get_level_display }}.png">
                        </div>
                    </td>
                    <td> <a href="{% url 'tests:details' id=test.id %}">DETAILS</a></td>
                </tr>
            {% endfor %}
        </table>

        <div class="p-1 m-1">
            {% include 'includes/pagination.html' %}
        </div>
    {% else %}
        <p>No tests yet :(</p>
    {% endif %}

{% endblock %}

src/testify/templates/question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load math_funcs %}

{% block header %}
    <h1>Question: {{ question.text }}?</h1>
    {% expr '(%1-1)/%2*100' question.order_number question.test.questions.count as progress %}
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width:{{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">{{ progress|floatformat:2 }}%</div>
        </div>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form_set.management_form}}

        Current question #{{ question.order_number }}/{{ question.test.questions.count }}

        {% for form in form_set %}

            <div class="mt-1">
                {{ form.is_selected }} <label>  {{ form.text.value }}</label>
            </div>
            <div class="mt-1">
                {{ form.text }}
            </div>
            <div class="mt-1">
                {{ form.id }}
            </div>

        {% endfor %}

        <button type="submit" class="btn btn-success">Next</button>
    </form>
{% endblock %}