src/accounts/urls.py
from accounts.views import AccountCreateView, AccountListView, AccountLoginView, AccountLogoutView, \
    AccountPasswordChangeView, AccountUpdateView, ContactView, LeaderboardListView

from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('', AccountListView.as_view(), name='users'),
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password'),
    path('leaderboard/', LeaderboardListView.as_view(), name='leaderboard'),
    path('contact_us/', ContactView.as_view(), name='contact_us'),
    ]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [

    # UI
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('testify/', include('testify.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    ]

handler404 = views.error_404
handler400 = views.error_400
handler403 = views.error_403
handler500 = views.error_500

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, TestDetailView, TestListView, TestRunnerView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% block title%}
    <title>Tests</title>
{% endblock %}
<style>

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>

<body>

{%url 'tests:list' as List %}
{%url 'accounts:leaderboard' as Leaderboard %}
{%url 'accounts:users' as Users %}
{%url 'accounts:profile' as Profile %}
{%url 'accounts:register' as Register %}
{%url 'accounts:login' as Login %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">Testify</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
            <ul class="navbar-nav ">

                {% if user.is_authenticated %}

                <li class="nav-item {% if request.path == List %} active {% endif %}">
                    <a class="nav-link" href="{% url 'tests:list' %}">Tests</a>
                </li>
                <li class="nav-item {% if request.path == Leaderboard %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:leaderboard' %}">Leaderboard</a>
                </li>
                <li class="nav-item {% if request.path == Users %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:users' %}">Users</a>
                </li>

                <li class="nav-item {% if request.path == Profile %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>

                <li class="img-circle.vert">
                    <img class="rounded-circle p-1 m-1" width="40" height="40" src=" {{ user.image.url }} ">
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:contact_us' %}">Contact us</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>

                {% else %}

                <li class="nav-item {% if request.path == Register %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>

                <li class="nav-item {% if request.path == Login %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>

                {% endif %}

            </ul>
      </div>
    </div>
</nav>
</div>

{% include 'includes/messages.html' %}

<div class="container">
    <div class="border border-white rounded-pill shadow p-3 mb-5 mt-5 bg-white rounded text-center">
        {% block header %}
            <h3>Welcome</h3>
        {% endblock %}
    </div>

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block header %}
    <h3>Navigation</h3>
{% endblock %}


{% block content %}

    <form>
        <input formaction="{% url 'accounts:leaderboard' %}" type="submit" class="btn btn-info" value="Leaderboard">
    </form><br>

    <form>
        <input formaction="{% url 'tests:list' %}" type="submit" class="btn btn-info" value="Tests">
    </form><br>

    <form>
        <input formaction="{% url 'accounts:users' %}" type="submit" class="btn btn-info" value="Users">
    </form>

{% endblock %}